version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_PASSWORD=my_password
    volumes:
      - /Users/esteban/Documents/Projects/laravel/udemyCourse/mariadb/:/mnt

  myapp:
    tty: true
    image: docker.io/bitnami/laravel:latest
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - /Users/esteban/Documents/Projects/laravel/udemyCourse/app/:/app