version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    container_name: MariaDB
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=estebanIbarra
      - MARIADB_DATABASE=udemyCourse
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_PASSWORD=
    ports:
      - 3307:3306
    volumes:
      - /Users/esteban/Documents/Projects/laravel/udemyCourse/mariadb/:/mnt

  laravel:
    tty: true
    image: docker.io/bitnami/laravel:latest
    container_name: Laravel
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=estebanIbarra
      - DB_DATABASE=udemyCourse
      - DB_PASSWORD=
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - /Users/esteban/Documents/Projects/laravel/udemyCourse/laravelApp/:/app